### ISSUE TITLE
Finish the game

### ISSUE THREAD

**Issue by nasivuela** [Adalab/f-m2-evaluacion-intermedia-younglust#1]
Really cool job @younglust  !!!

Here you have some tips to improve the exercise:

- [x] Enable Strict mode by writing 'use strict' at the beginning of the js document
- [x] If you call 'getRandomNumer' function inside the event callback, you will be creating a new random number each time the user clicks the button. That makes the game really complex and the hints will not have sense. Let's generate the random number when the page loads instead.
- [x] Remember to convert input value string to a number
- [x] Move variables and constants declarations to the top of the file
- [x] Write your classes in English!
- [x] Use a `label` to define the content of the input

Let me know if you have any doubts ;)

Go for it!!

**Comment by younglust** [comment]
Hello Nasiba, I think I fixed the issue and add a new button :). Thank you!!

**Comment by nasivuela** [comment]
Good work @younglust !!

Here you have more improvements

- [ ] Connect label and input (with for and id attributes)
- [ ] Fix the type attribute of your buttons
- [ ] After resetting the game, if you start another round the counter looks wrong.
- [ ] Move the feedback logic to a function an execute it on each click
- [ ] Move you counter logic into a function and execute it on each click
- [ ] You are writing many times "parrafMain.innerHTML = 'something';", what about making a function that accepts a string as param and paints it into 'parrafMain'?

Then you can improve the game as you please, here you have some ideas:

-You have some variables with the feedback texts, sweet! Since they are related, another way to organize it is to have an object to store them.

```
const feedbackText = {
  winner: "¡HAS GANADO, CAMPEONA!",
  big: "...."
};
```
- Only allow numbers in the input.
- Add new feedback when the number is bigger than 100 or smaller than 0.
- Manage when the user hits the button and the input is empty.
- Make the input work when hitting the enter key.
- Whatever you want!

**Comment by younglust** [comment]
Hello again @nasivuela 
I did all the new improvements.
I did too an object with the feedback texts and with that I did the checklist number 6, but I'm not sure if that way it's ok. I'll try to do the others ideas you gave me :) Thank you again

**Comment by nasivuela** [comment]
Your object is cool! 

Maybe you have complicated a little access to values when converting the object to array and accessing by index. 

A simpler way to do it would be accessing the strings by property name, and passing them directly to the feedback painter function:
```
getFeedbackTexts(feedbackTextGame.low)
```

PD. Watch out that '</figure>' on HTML

Anyway, it looks amazing!

![](https://media.giphy.com/media/cGEWR5jiq9AWc/giphy.gif)
